from django import forms

class CancerDiseaseForm(forms.Form):
    id = forms.IntegerField(label='id', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter id'}))
    diagnosis = forms.TypedChoiceField(label='diagnosis', choices=[(1, 'M'), (0, 'F')], coerce=int, widget=forms.Select(attrs={'class': 'form-control'}))
    radius_mean = forms.FloatField(label='radius_mean',  widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter radius_mean'}))
    texture_mean= forms.FloatField(label='texture_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter texture_mean'}))
    perimeter_mean = forms.FloatField(label='perimeter_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter perimeter_mean'}))
    area_mean = forms.FloatField(label='area_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter area_mean'}))
    smoothness_mean = forms.FloatField(label='smoothness_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter smoothness_mean'}))
    compactness_mean = forms.FloatField(label='compactness_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter compactness_mean'}))
    concavity_mean = forms.FloatField(label='concavity_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter concavity_mean'}))
    concave_points_mean = forms.FloatField(label='concave points_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter concave points_mean'}))
    symmetry_mean = forms.FloatField(label='symmetry_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter symmetry_mean'}))
    fractal_dimension_mean = forms.FloatField(label='fractal_dimension_mean', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter fractal_dimension_mean'}))
    radius_se = forms.FloatField(label='radius_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter radius_se'}))
    texture_se = forms.FloatField(label='texture_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter texture_se'}))
    perimeter_se = forms.FloatField(label='perimeter_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter perimeter_se'}))
    area_se = forms.FloatField(label='area_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter area_se'}))
    smoothness_se = forms.FloatField(label='smoothness_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter smoothness_se'}))
    compactness_se = forms.FloatField(label='compactness_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter compactness_se'}))
    concavity_se = forms.FloatField(label='concavity_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter concavity_se'}))
    concave_points_se = forms.FloatField(label='concave points_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter concave points_se'}))
    symmetry_se = forms.FloatField(label='symmetry_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter symmetry_se'}))
    fractal_dimension_se = forms.FloatField(label='fractal_dimension_se', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter fractal_dimension_se'}))
    radius_worst = forms.FloatField(label='radius_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter radius worst'}))
    texture_worst = forms.FloatField(label='texture_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter texture worst'}))
    perimeter_worst = forms.FloatField(label='perimeter_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter perimeter worst'}))
    area_worst = forms.FloatField(label='area_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter area worst'}))
    smoothness_worst = forms.FloatField(label='smoothness_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter smoothness worst'}))
    compactness_worst = forms.FloatField(label='compactness_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter compactness worst'}))
    concavity_worst = forms.FloatField(label='concavity_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter concavity worst'}))
    concave_points_worst = forms.FloatField(label='concave_points_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter concave_points_worst'}))
    symmetry_worst = forms.FloatField(label='symmetry_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter symmetry_worst '}))
    fractal_dimension_worst = forms.FloatField(label='fractal_dimension_worst', widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter symmetry_worst '}))


